### ISSUE TITLE
Some user preferences are not saved / loaded correctly.

### ISSUE THREAD

**Issue by VirtualPedestrian** [EmiyaSyahriel/CrossLauncher#2] opened 2020-11-30 11:42 UTC
The setting reset itself when the launcher isn't used for example if I hide clock bar and then restart my phone the launcher will show clock bar

**Comment by VirtualPedestrian** [comment] 2020-12-11 15:52
BTW stupid question: can you make it work with emulator e.q PPSSPP like front end emulator  
![Emulator-Frontend](https://user-images.githubusercontent.com/73787177/101924661-e89f6880-3c0b-11eb-889a-9f4a3b05e4f0.png)

**Comment by EmiyaSyahriel** [comment] 2020-12-19 20:49
I don't think I can make it as another app front end unless their API can be hooked from Android Runtime. I already tried once during project initial phase with [J2ME-Loader](https://github.com/nikita36078/J2ME-Loader) which have it's own directory in device storage and it is easy to launch via Android Runtime. But, it was very hacky and buggy due to Android permissions and inconsistency between the data I sent from this launcher to the app via Intent.

Or maybe I can implement a plugin architecture in this launcher for other developers to make a binding from their app and add their sub-games to their own special list in this launcher.

For other Feature request amd Ideas, please use the newly-made [Discussion Page](https://github.com/EmiyaSyahriel/CrossLauncher/discussions/categories/ideas).

**Comment by EmiyaSyahriel** [comment] 2023-08-25 04:43
Since this bug report scope is very general, I'll took the context of what is reported in this report in the first place (back at 2020), All of the user preference bug up to this report should've already been fixed. And therefore I want to close this bug report.

But, I'd like to ask @VirtualPedestrian for feedback before I close this report, If there is still any of this bug happening and is reproducible, please let me know in this bug report before 07 September where I close this report. You can still re-open it after that though.

**Comment by EmiyaSyahriel** [comment] 2023-09-08 03:52
Closed, assuming Issue Resolved.

**Closed by EmiyaSyahriel** 2023-09-08 03:52 UTC
Labels: bug
